
CREATE TABLE [dbo].[Reserva](
[ID] INT IDENTITY(1,1) NOT NULL,
[IGG] VARCHAR(20) NOT NULL,
[EventoID] INT NOT NULL,
[SalaID] INT NULL,
[BandaID] INT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Evento](
[ID] INT IDENTITY(1,1) NOT NULL,
[Titulo] VARCHAR (200) NOT NULL,
[Fecha_inicio] DATETIME NOT NULL,
[Fecha_fin] DATETIME NULL,
[Descripcion] VARCHAR (200) NULL,
) ON [PRIMARY]

CREATE TABLE [dbo].[Administrador](
[IGG] VARCHAR(200) NOT NULL,
[Nombre] VARCHAR (200) NOT NULL,
) ON [PRIMARY]

CREATE TABLE [dbo].[Banda](
[ID] INT IDENTITY(1,1) NOT NULL,
[Fecha] DATETIME NOT NULL,
[Horario_inicio] TIME NOT NULL,
[Horario_fin] TIME NULL,
[SalaID] INT NULL,
) ON [PRIMARY]

CREATE TABLE [dbo].[Sala](
[ID] INT IDENTITY(1,1) NOT NULL,
[Cupo] VARCHAR(200) NOT NULL,
[Nombre] VARCHAR(200) NOT NULL,
[Ubicacion] VARCHAR(200) NULL,
) ON [PRIMARY]

