
ALTER TABLE Reserva
ADD FOREIGN KEY (BandaID) REFERENCES Banda(ID);


ALTER TABLE Reserva
ADD FOREIGN KEY (SalaID) REFERENCES Sala(ID);


ALTER TABLE Reserva
ADD FOREIGN KEY (EventoID) REFERENCES Evento(ID);


ALTER TABLE Banda
ADD FOREIGN KEY (SalaID) REFERENCES Sala(ID);